[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#[build]
#rustflags = ["-Clink-arg=-fuse-ld=lld"]

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
